name: Multi-OS

on: [push]

jobs:
  run-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Ejecutar uname
        run: uname -a
        shell: bash
